### PR TITLE
fix(alerts): remove volume

### LINKED ISSUE #333: alert- failure due to lack of space
since we already update alert space size 3times, we should investigate a better solution
- investigate clone options https://www.git-scm.com/docs/git-clone#Documentation/git-clone.txt---shallow-sinceltdategt
- refactor how the script works to handle a stream of version and produce a stream of alert (stream does not explicitely refers to node stream of rxlike stream

### PR DESCRIPTION
**Pull request by lionelB**
- alert will only clone repo history since the last run, 
- alert volume hab been removed
- alerts are compute and then store to avoid keeping all alerts in memory

close #333

### CODE REVIEW

File: targets/alert-cli/src/openRepo.js [hunk 1]
```diff
@@ -29,9 +29,29 @@ export async function openRepo({ repository }) {
...
+    /**
+     * The option --shallow-exclude ${tag}
+     * allow us to only clone repo with history limited to a given revision (or tag)
+     * that way we do not clone the entire history nor fetch all the existing tag
+     */
+    const command = `git clone --shallow-exclude ${tag} --bare https://github.com/${org}/${repositoryName} ${localPath}`;
+    console.log(command);
+    await exec(command);
+    /**
+     * Since swallow exlude remove our base tag, we need to add it
```
Comment (UnbearableBear) [inline targets/alert-cli/src/openRepo.js:42]: I’m having troubles understanding that one: basically we get the repo at one tag, which is excluded, and then we get that tag with deepen ? Nice and straightforward but I find the comments slightly confusing.
Also, is it possible that the previous commit won’t be the one with the tag at some point ?
Could we simply compute the previous tag directly shallow-exclude on it so we don’t have to `deepen` ? (beware the 0.1.0 corner case)

File: targets/alert-cli/src/index.js [hunk 2]
```diff
@@ -8,13 +9,13 @@ import { processDilaDiff } from "./diff/dila";
...
 import { exportContributionAlerts } from "./exportContributionAlerts";
-import { getFicheServicePublicIds } from "./getFicheServicePublicIds";
+import { getFicheServicePublicIds as _getFicheServicePublicIds } from "./getFicheServicePublicIds";
 import { getFilename } from "./node-git.helpers";
 import { openRepo } from "./openRepo";
 
 const sourcesQuery = `
 query getSources {
-  sources {
+  sources(where: {repository: {_like: "%kali%"}}) {
```
Comment (UnbearableBear) [inline targets/alert-cli/src/index.js:18]: leftovers

File: targets/alert-cli/src/openRepo.js (hunk 1 above)
Comment (lionelB) [reply targets/alert-cli/src/openRepo.js:42]: the script only run between versions, and version are released only if data is updated.
so even if previous commit is a not a release, it's not a problem because we know that data had been modified between that commit and the next release

**Review by UnbearableBear — APPROVED** [review]
👏

File: targets/alert-cli/src/index.js (hunk 2 above)
Comment (lionelB) [reply targets/alert-cli/src/index.js:18]: oups.....

File: targets/alert-cli/src/index.js [hunk 3]
```diff
@@ -199,110 +204,89 @@ async function getNewerTagsFromRepo(repository, lastTag) {
...
+  const [prevTree, currTree] = await Promise.all([
+    previousCommit.getTree(),
+    currentCommit.getTree(),
+  ]);
+  const diff = await currTree.diff(prevTree);
+  const patches = await diff.patches();
 
-  const fileFilter = getFileFilter(repositoryId, ficheVddIDs);
-  const diffProcessor = getDiffProcessor(repositoryId);
+  const files = patches.map(getFilename).filter(fileFilter);
```
Comment (m-maillot) [inline targets/alert-cli/src/index.js:225]: I think we can inline this call :
```js
const files = await currTree.diff(prevTree).patches().map(getFilename).filter(fileFilter);
```
I think it's more readable because methods are self-explanatory.

**Review by m-maillot — APPROVED** [review]
Nice optimization!

File: targets/alert-cli/src/index.js (hunk 3 above)
Comment (lionelB) [reply targets/alert-cli/src/index.js:225]: since patches() method is async we need to add parenthesis before map / filter
```js
const files = (await currTree.diff(prevTree).patches()).map(getFilename).filter(fileFilter);
```

Comment (m-maillot) [reply targets/alert-cli/src/index.js:225]: Yes, indeed. It's more ugly with await. Perhaps two lines :
```js
const patches = await currTree.diff(prevTree).patches()
const modifiedFiles = patches.map(getFilename).filter(fileFilter);
```
What do you think?

Comment (lionelB) [reply targets/alert-cli/src/index.js:225]: diff() method is async too
```js
const patches = await (await currTree.diff(prevTree)).patches()
const modifiedFiles = patches.map(getFilename).filter(fileFilter);
```

Comment (m-maillot) [reply targets/alert-cli/src/index.js:225]: 🤦 Ok, I'll go to the bed, I'll see you tomorrow 😄 (I close this discussion).
